### ISSUE TITLE
Sign up and test the current Gen 2 Platform

### ISSUE THREAD

**Issue by aflies1** [promazo/Gen2-Consulting#11]
Sign up, create your profile, Input 1-3 target internship/full-time position. Try and navigate through the entire platform. Submit any bug/issues/comments on the site to complete. Move the task to done when ready to compile thoughts and findings.

**Comment by irynakmyts** [comment]
Hi, guys!
Please follow this link to see my review: https://docs.google.com/document/d/1X45W0vfX3DBdldf6f3TgCCpDfwCfx4zAWcYqbGUo4p4/edit?usp=sharing

All the best,
Iryna
